buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // IS LINE KO UPGRADE KARO: 8.2.0 se 8.7.3
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.21"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
