// Top-level build file
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Yeh plugin yahan sirf 'classpath' ke roop mein hona chahiye
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
    }
}

allprojects {
    // Is block ko ab hata sakte hain kyunki settings.gradle handles it
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
