buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
        // YAHAN CHANGE KARO: 1.9.0 ko 2.0.21 kar dein
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.21"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
