pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    // YAHAN BADLAV HAI: FAIL_ON_PROJECT_REPOS ki jagah PREFER_SETTINGS karein
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "UdaanChild"
include ':app'
