apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    // Dono tarike likh dete hain taaki koi doubt na rahe
    compileSdk 36
    compileSdkVersion 36 

    namespace 'com.udaan.child'

    defaultConfig {
        applicationId "com.udaan.child"
        minSdk 29
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    
    // ... (baaki sab same rahega)
}
// ... (dependencies same rahengi)
