apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    // Dono lines likhein taaki koi shak na rahe
    compileSdk 36
    compileSdkVersion 36 

    namespace 'com.udaan.child'

    defaultConfig {
        applicationId "com.udaan.child"
        minSdk 29
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }
    // ... baaki sab same rahega
}
